### ISSUE TITLE
Console volume not adjustable

### ISSUE THREAD

**Issue by Graviter** [rg35xx-cfw/Koriki#20]
### What happened?

Console volume not adjustable.
Console boot only witch "bootfix_for_some_revisions.zip". When press the volume buttons, the volume itself is not adjusted. but I can adjust the brightness with the volume buttons.

**Comment by fender357** [comment]
I've noticed this one as well.

**Comment by acmeplus** [comment]
bootfix needs to be upgraded for the latest koriki releases (0.8, 0.9). I no longer have access to one of the units that requires this fix (typically rg35xx v6.0C) so I'll try to put a new fix together to see if that solves the issue.

**Comment by Graviter** [comment]
Work with new fix
