### ISSUE TITLE
how can i set custom cpu speed? [cooling mod]

### ISSUE THREAD

**Issue by whoodealley** [rg35xx-cfw/Koriki#48]
### What happened?

Hey, how can i set custom cpu speed? i modded rg35xx cooling adding copper plate, thermal glue nad some radiator, temps go down significant. I can add small fan, it will be fun to modding this handheld. Is this possible? If this will be practical i can do a custom set, and tutorial to everyone can do this at own, cheap easy with no skills.

**Comment by whoodealley** [comment]
![PXL_20230809_083032697](https://github.com/rg35xx-cfw/Koriki/assets/137226242/5c751aeb-df52-466e-aac7-beae0c918a65)
ok, i manage this on my own i set the cpu to 1600mhz on my cool mod and dreamcast shenmue giving smooth gameplay at stock settings with 60 celcius at most demanding game.

**Comment by acmeplus** [comment]
That's really cool. I'm sure many will be interested on your tutorial, so please post it when you have time.
