### ISSUE TITLE
Downloading koriki creates partition on the sd card that has an error and cant be removed or else koriki wont boot

### ISSUE THREAD

**Issue by Louisvanleuven** [rg35xx-cfw/Koriki#49]
### What happened?

my sd card just got corrupted when booting koriki after adding some psp and ds roms I have no idea why considering I was careful with my sd card and its not the one from the rg35xx its one from evo plus. So I decided to just do another install of koriki, each time I flash the sd card it creates a weird partition that i cant open and gives an error which makes me try to repair it which i just ignored before, But maybe it contributed to my sd card getting corrupted? and my pc constantly asking to repair the partition is also pretty annoying, so I was wondering if its possible to just get rid of this strange partition without making it not work anymore. Any help on preventing my sd card from getting corrupted is also greatly appreciated :).

**Comment by benni092** [comment]
A huge amount of writes to an sd-card can make it read only due to the flash cells are dying.

Can you confirm that you can write to the card? Format it to normal and copy some files to it, than make a eject-cycle and lock at the files if they are still there.

By the way how did you flash the image to the card?

Windows or linux?

**Comment by kvhagberg** [comment]
there are several partions that are not fat32, These partions are linux ext4 partions and contain valid data that is needed as the running os is linux.

**Comment by Louisvanleuven** [comment]
> 

I flash my sd cards with windows balena etcher. I can write to the card, it is pretty new like 2 weeks old and after doing an eject-cycle (I dont really know how to set that up so I just ejected it 20 times manually) and no file dissapeared. I think the reason my sd card got corrupted was because I was stupid and I ignored it when winows said there was something wrong with the batocera partition and tried to scan it cause I thought it'd do something with the sd card or because I'm using a pretty fragile sd card reader from a sf2000. Im very sorry for bothering you, im pretty sure it was just personal fault. is there any way to remove this issue considering it isnt really an issue with koriki? Thankyou very much for your comment though ill try not to write to much to it :)

**Comment by Louisvanleuven** [comment]
> A huge amount of writes to an sd-card can make it read only due to the flash cells are dying.
> 
> Can you confirm that you can write to the card? Format it to normal and copy some files to it, than make a eject-cycle and lock at the files if they are still there.
> 
> By the way how did you flash the image to the card?
> 
> Windows or linux?

I flash my sd cards with windows balena etcher. I can write to the card, it is pretty new like 2 weeks old and after doing an eject-cycle (I dont really know how to set that up so I just ejected it 20 times manually) and no file dissapeared. I think the reason my sd card got corrupted was because I was stupid and I ignored it when winows said there was something wrong with the batocera partition and tried to scan it cause I thought it'd do something with the sd card or because I'm using a pretty fragile sd card reader from a sf2000. Im very sorry for bothering you, im pretty sure it was just personal fault. is there any way to remove this issue considering it isnt really an issue with koriki? Thankyou very much for your comment though ill try not to write to much to it :)

**Comment by Louisvanleuven** [comment]
> there are several partions that are not fat32, These partions are linux ext4 partions and contain valid data that is needed as the running os is linux.

Yes, thankyou very much. I wasnt really sure what to do with that partition cause it was constantly giving me errors when windows tried to open it, but I just didn't assign it a letter and now it doesn't show up anymore, Its still on the sd card but its just not giving me any errors anymore.

**Comment by acmeplus** [comment]
Yes, the system creates a hidden swap partition that is not intended to be read, so that may be part of the issue. Just ignore that. The only partitions that should be accesible are the BATOCERA (boot, kernel, system files, etc.) and SHARE (roms, bios and general user content).

**Comment by Louisvanleuven** [comment]
> Yes, the system creates a hidden swap partition that is not intended to be read, so that may be part of the issue. Just ignore that. The only partitions that should be accesible are the BATOCERA (boot, kernel, system files, etc.) and SHARE (roms, bios and general user content).

Ah alright thankyou, at first windows constantly tried to open that partition and reformat it but after doing another flash that doesn't happen anymore.
