### ISSUE TITLE
GBA saves not work from v0.9.1 to v0.9.2

### ISSUE THREAD

**Issue by SzalikDesigns** [rg35xx-cfw/Koriki#72]
### What happened?

i just simply copy them in retroarch directory, but they not loading, any reason for that?

**Comment by acmeplus** [comment]
Check the save states path in retroarch configuration. Retroarch -> Settings -> Directories -> Save States

**Comment by SzalikDesigns** [comment]
i did, i copy paste them correctly, however they still failed to load, did you swap core?

**Comment by acmeplus** [comment]
No, 0.9.2 does not contain any core changes.

**Comment by SzalikDesigns** [comment]
just to clarify i made this saves by clicking menu + r1 and trying to load them same way, maybe this will help you to help me or replicate : )

However i want to mention, that GBA emulation improved alot in 0.9.2 it was so laggy before on pokemon hacks like GS Chronicles that i keep playing with fast forward to make it normal speed lol, and music was broken on this heavy rom hacks on 0.9.1, but now its much better ( you asked to say what's improved so here it is )
