### ISSUE TITLE
The v1.0 image file does not fit on FAT32-formatted SD card

### ISSUE THREAD

**Issue by Additional-Pylons** [rg35xx-cfw/Koriki#86]
### What happened?

I downloaded the latest release - koriki-rg35xx-v1.0_20231112.img.gz
I have a 64GB SD card
I formatted the card with FAT32 using HPUSBDisk.exe (also tried guiformat.exe)
I am using WinRAR to try to unpack the img file directly onto my SD card
Windows reports the unpacked img file size is 4,202,496KB

WinRAR fails with this error message:
There is not enough disk space on the disk. Write error: only NTFS file system supports larger than 4GB

If I try to unpack the img file onto my own hard drive and then copy it to the SD card, the error message I get is:
The file 'batocera-rg35xx-rg35xx--20231112.img' is too large for the destination file system.

**Comment by benni092** [comment]
Try to flash the .tgz file with balena etcher.

**Comment by Additional-Pylons** [comment]
Ah, that worked, thanks!  I followed the wiki link from the README.md over to the main Koriki github repository and tried to follow their install instructions.  Would it make sense to remove those links from the README.md?

**Comment by Additional-Pylons** [comment]
I'll let the maintainers make the decision about whether a README.md change makes sense.  I'll go ahead and close this since I wasn't following the instructions in this repository :)  Thanks again for your help!
